### ISSUE TITLE
Fractal Programming

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Computer-Graphics#26]
Create OpenGL code for Fractals.

**Comment by jmnorma** [comment]
Hi NishkarshRaj, 
     My name is Josh Norman. I am a junior computer science major at Clemson University. I was wondering if this issue is still available? if so may I take it?

**Comment by NishkarshRaj** [comment]
Hello @jmnorma 
Yes, this issue is still open. I am assigning this to you.
Write the code for Fractals and raise a PR by putting the code in the following path:

```
OpenGL/Fractals
```

**Comment by EkanshMangal** [comment]
Hey Nishkarsh,
is this issue still available as i have worked in fractals?

**Comment by NishkarshRaj** [comment]
@EkanshMangal yes you can work on this, it is still open :+1:

**Comment by NishkarshRaj** [comment]
@jmnorma Thanks for completing the task. :smile: 
@EkanshMangal This is completed now. :+1: 

Done in #34
