### ISSUE TITLE
GitHub Action setup

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Computer-Graphics#8]
Want to copy .cpp file in container and print its OpenGL output in the container.
Does not work
Exits Docker container with exit ID 1.

**Comment by shiftkey** [comment]
https://github.com/NishkarshRaj/Computer-Graphics/blob/c4c44c28e3d0f41bde2f1bee413e2badd6df7b9b/action-a/Dockerfile#L4-L5

These lines should not be wrapped in quote marks, which I think is causing Docker to try and run them in a different way.

I think it should look like this:

```
RUN apt-get install g++
RUN chmod +x script1.sh
```

The Docker documentation is worth a to wrap your head around the syntax readhttps://docs.docker.com/engine/reference/builder/#run

**Comment by shiftkey** [comment]
https://github.com/NishkarshRaj/Computer-Graphics/blob/fc0644814322841c936a54c4441ea655317f72a7/action-a/Dockerfile#L2-L6

The other thing to note is what the container tries to do when you run it up:

- You're adding `script1.sh` to the root of the filesystem
- But `ENTRYPOINT` is set to just run `script1.sh` (this assumes it's on your PATH)
- And [at runtime](https://github.com/NishkarshRaj/Computer-Graphics/commit/af1002f2ffec57223dd1cf5f46765bb023e21b0c/checks?check_suite_id=357273335#step:3:71) docker indicates that `script1.sh` is not on PATH and errors because it cannot be found.

```
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"script1.sh\": executable file not found in $PATH": unknown.
```

If you look at the command that runs you'll see that the working directory is `/github/workspace`:

```
/usr/bin/docker run --name af96b4102267eac6f850e5e2ae674a50bf9349_96e62c --label af96b4 --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/Computer-Graphics/Computer-Graphics":"/github/workspace" af96b4:102267eac6f850e5e2ae674a50bf9349
```

I'd recommend just changing `ENTRYPOINT` to run `/script1.sh` as that should work.

**Comment by NishkarshRaj** [comment]
@shiftkey Thanks alot for your recommendations.
I did made the changes in RUN command syntax and the script file location.

Still, I am not getting results. But this time I don't think its my fault.
I am using ubuntu-latest as my machine which is not supporting free-glut3 dev package for OpenGL which it does for ubuntu on my Laptop.

I don't know why it is not supported in Actions or by Docker machine but I am getting the error that this package does not exist in our library.

**Comment by shiftkey** [comment]
@NishkarshRaj ensure you do an `apt-get update` before trying to install a package - it may not be cached locally

**Comment by NishkarshRaj** [comment]
@shiftkey sir, I tried both updating and upgrading but I am facing a new error.
It is asking Y/n for updating but since no input is given at runtime, it exits with error id. 😢

**Comment by shiftkey** [comment]
@NishkarshRaj there's a flag to use for just this situation https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install

I'd also look at testing your Dockerfiles locally before committing and pushing as it's a great way to catch problems like these.

**Comment by NishkarshRaj** [comment]
@shiftkey the use of -y flag helped us to get green tick for successful implementation.
Still, I cannot see my output because for some reason, Actions has yet not started for the latest commit 🤣 
And please help me with the local environment.

**Comment by NishkarshRaj** [comment]
Sir, all installations were successful but script is not executing.
I have switched from Entrypoint to CMD command. Please check it out.

**Comment by shiftkey** [comment]
I think you're going to have a problem with this line, because it's trying to run from the current directory (I'm not sure where the program is being compiled to):

https://github.com/NishkarshRaj/Computer-Graphics/blob/6c213398d3a83885589132eed4e2673146f1fc44/action-a/script1.sh#L3

> And please help me with the local environment.

I've used [this setup guide](https://docs.docker.com/install/linux/docker-ce/ubuntu/) before for Ubuntu.

**Comment by NishkarshRaj** [comment]
@shiftkey Thanks for the tutorial, I have updated the Dockerfile with WORKDIR command to resolve any location related ambiguities. All the files now reside on /root/nish directory which is also my working directory.
I am still facing some issues but its high time I crash today. I will give a follow up tomorrow. Thanks for the help today sir 😄

**Comment by NishkarshRaj** [comment]
@shiftkey Finally, I have resolved this issue completely. Actions is now running fine. Thanks a lot sir 😃

**Comment by NishkarshRaj** [comment]
> I think you're going to have a problem with this line

Regarding this sir, Actions run the Dockerfile automatically but it does not run it in interactive mode. How can we see the output after its execution?

**Comment by shiftkey** [comment]
> Regarding this sir, Actions run the Dockerfile automatically but it does not run it in interactive mode. How can we see the output after its execution?

I'm not sure what exactly you're asking for, but there's a support forum available for GitHub Actions here: https://github.community/t5/GitHub-Actions/bd-p/actions

**Comment by NishkarshRaj** [comment]
In #29 PR, I am not using the script1.sh file which is not getting executed despite being present as checked by ls and pwd command.
The new problem that arises is that ./a.out command is not getting executed despite successful execution of the .cpp file.

**Comment by NishkarshRaj** [comment]
@shiftkey I have completely solved the issue with the help of the Community forum and your help.
Here are the biggest key takeaways of this issue resolution:

1. RUN command does not take inputs in " " for Dockerfile
2. Use "sudo apt-get -y install <packagename>" for automatically sending Yes input during installation.
3. Docker standards do not support multiple CMD commands. Thus, if multiple CMD commands are used, only last CMD command is executed.
4. The workspace of execution of scripts in Docker using GitHub Actions are root of the repository.
Thus the file to be used in g++ command must be given absolute path relative to root repository.
Here, ```g++ action-a/Hut.cpp``` is used
5. Containers cannot give output even though ./a.out file is successfully executed.

Link to forum: https://github.community/t5/GitHub-Actions/How-to-run-Docker-in-interactive-mode/m-p/41373#M4600
