### ISSUE TITLE
Fill Algorithms

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Computer-Graphics#9]
Flood fill and boundary fill algorithms not working.

**Comment by EkanshMangal** [comment]
Hey Nishkarsh
Is the problem solved or still need to be solved?

**Comment by NishkarshRaj** [comment]
Issue still open @EkanshMangal

**Comment by amrii1** [comment]
Hello,
Is the problem solved or still need to be solved?

**Comment by NishkarshRaj** [comment]
@amrii1 not solved yet.

**Comment by amrii1** [comment]
Could you please describe the issue because i run FloodFill.cpp in my computer and the rectangle was filled with red color

**Comment by amrii1** [comment]
Hello,
I noticed that the (x,y) parameters in onMouseClick (FloodFill.cpp) are hardcoded. So i did the following.
I declared these two global variables:
const int WIDTH = 480;
const int HEIGHT = 640;

and added some changes to onMouseClick:
void onMouseClick(int button, int state, int x, int y)
{
	Color newColor = {1.0f, 0.0f, 0.0f};
	Color oldColor = {1.0f, 1.0f, 1.0f};
	int halfWidth = WIDTH/2;
	if(y > halfWidth) 
	{
		y -= (y-halfWidth)*2;
	}
	else
	{
		y += (halfWidth-y)*2;
	}
	floodFill(x, y, oldColor, newColor);
}

I hope this would solve your issue

**Comment by NishkarshRaj** [comment]
@amrii1 Thanks a lot for spending time and solving the issue. 👍 
To get the credit for the solution, please create a pull request and reference it here.

**Comment by NishkarshRaj** [comment]
Thanks @amrii1 
Closed in #35
